org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true


minecraft_version=1.21.11

# Mod properties
mod_version=1.21.11-1.15.0
maven_group=com.vsngarcia
archives_name=elevatorid
enabled_platforms=fabric,neoforge

# Dependencies
fabric_loader_version=0.18.2
fabric_api_version=0.140.0+1.21.11
neoforge_version=21.11.6-beta

forge_config_api_port_version=21.11.1
