org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true


minecraft_version=1.21.7

# Mod properties
mod_version=1.21.7-1.14.2
maven_group=com.vsngarcia
archives_name=elevatorid
enabled_platforms=fabric,neoforge

# Dependencies
fabric_loader_version=0.16.14
fabric_api_version=0.129.0+1.21.7
neoforge_version=21.7.19-beta

forge_config_api_port_version=21.7.0
