org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true


minecraft_version=1.21.8

# Mod properties
mod_version=1.21.8-1.14.4
maven_group=com.vsngarcia
archives_name=elevatorid
enabled_platforms=fabric,neoforge

# Dependencies
fabric_loader_version=0.17.2
fabric_api_version=0.133.4+1.21.8
neoforge_version=21.8.46

forge_config_api_port_version=21.8.1
