modLoader = "javafml"
issueTrackerURL = "https://github.com/VsnGamer/ElevatorMod/issues/"
license = "MIT"

[[mods]]
modId = "elevatorid"
version = "${version}"
displayName = "ElevatorMod"
authors = "VsnGamer"
logoFile = "logo.png"
credits = "OpenBlocks Team"
displayURL = "https://github.com/VsnGamer/ElevatorMod"
description = '''Simple port of the elevator from OpenBlocks to 1.8+'''

[[dependencies.elevatorid]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.0.1-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.elevatorid]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "elevatorid.mixins.json"
