name: Publish

on:
  release:
    types: [ published ]

env:
  MODRINTH_ID: hi2dSXTu
  CURSEFORGE_ID: 250832

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin

      - uses: gradle/actions/setup-gradle@v6

      - run: ./gradlew build

      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            fabric/build/libs/
            neoforge/build/libs/

  publish-fabric:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Publish Fabric
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ env.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: ${{ env.CURSEFORGE_ID }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          files: fabric/build/libs/!(*-raw).jar
          name: "[Fabric] ElevatorMod ${{ github.event.release.tag_name }}"
          version: fabric-${{ github.event.release.tag_name }}
          version-type: ${{ github.event.release.prerelease && 'beta' || 'release' }}
          changelog: ${{ github.event.release.body }}
          loaders: fabric

  publish-neoforge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Publish NeoForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ env.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: ${{ env.CURSEFORGE_ID }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          files: neoforge/build/libs/!(*-raw).jar
          name: "[Neo] ElevatorMod ${{ github.event.release.tag_name }}"
          version: neoforge-${{ github.event.release.tag_name }}
          version-type: ${{ github.event.release.prerelease && 'beta' || 'release' }}
          changelog: ${{ github.event.release.body }}
          loaders: neoforge
