name: Publish

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: Release type
        required: true
        type: choice
        options:
          - release
          - beta
      targets:
        description: Publish targets
        required: true
        type: choice
        options:
          - all
          - fabric
          - neoforge

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Read version
        id: version
        run: |
          VERSION=$(grep --max-count=1 '^mod_version' gradle.properties | cut --delimiter='=' --fields=2 | tr --delete=' ')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Check tag doesn't already exist
        if: inputs.targets == 'all'
        run: |
          if git rev-parse "refs/tags/${{ steps.version.outputs.version }}" >/dev/null 2>&1; then
            echo "::error::Tag '${{ steps.version.outputs.version }}' already exists."
            exit 1
          fi

      - uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin

      - uses: gradle/actions/setup-gradle@v6

      - run: gradle clean build

      - name: Publish Fabric
        if: inputs.targets == 'all' || inputs.targets == 'fabric'
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: hi2dSXTu
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 250832
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-tag: ${{ steps.version.outputs.version }}
          files: fabric/build/libs/!(*-@(dev|sources|javadoc|shadow|raw)*).jar
          name: "[Fabric] ElevatorMod ${{ steps.version.outputs.version }}"
          version: fabric-${{ steps.version.outputs.version }}
          version-type: ${{ inputs.version-type }}
          loaders: fabric

      - name: Publish NeoForge
        if: inputs.targets == 'all' || inputs.targets == 'neoforge'
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: hi2dSXTu
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 250832
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-tag: ${{ steps.version.outputs.version }}
          files: neoforge/build/libs/!(*-@(dev|sources|javadoc|shadow|raw)*).jar
          name: "[Neo] ElevatorMod ${{ steps.version.outputs.version }}"
          version: neoforge-${{ steps.version.outputs.version }}
          version-type: ${{ inputs.version-type }}
          loaders: neoforge
